version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  chat:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis